### ISSUE TITLE
Installation instructions in README.md are incorrect

### ISSUE THREAD

**Issue by cranky-hub** [cPanelTechs/SysSnapv2#1]
Hi,

I just attempted to install the script via the instructions in README.md however they are incorrect. The instructions are missing "&&" before "cd /root/"

Here is what it should be;

``` wget -O /root/sys-snap.pl https://raw.githubusercontent.com/cPanelTechs/SysSnapv2/master/sys-snap.pl && cd /root/ && chmod 744 sys-snap.pl && perl sys-snap.pl --start ```

**Comment by cPanelBryan** [comment]
Hello,

Thank you for finding this. I have updated the README.md with your correction.
